"use client"

import { type Metadata } from "next";
import { Provider, useDispatch, useSelector } from "react-redux";
import { store, RootState, AppDispatch } from "@/lib/store";
import "./globals.css";
import AuthGaurd from "@/components/AuthProtection"
import { useEffect } from "react";
import { loginUser } from "@/lib/user/userSlice";
import { useRouter } from "next/navigation";


const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body>
        <Provider store={store}>
          {children}
        </Provider>
      </body>
    </html>
  );
}
